version: "3.9"

services:
  db:
    image: postgres:18
    container_name: feed-postgres
    environment:
      POSTGRES_DB: FeedDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RonaldoRonaldo_777
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d FeedDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: feed-backend
    container_name: feed-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: FeedDb
      DB_USER: postgres
      DB_PASSWORD: RonaldoRonaldo_777
    ports:
      - "5000:8080"
    restart: always

volumes:
  postgres-data: